\documentclass[a4paper,11pt]{article}
\usepackage{mathpazo}
\usepackage{graphicx}
\usepackage{geometry}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{
 pdfstartview={XYZ null null 1}}
\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
#opts_chunk$set(fig.path='figure/minimal-', fig.align='center', fig.show='hold')
#options(formatR.arrow=TRUE,width=90)
@

\section{Data Summary}
Data analysis for the experiments of Jordan Lane and John Purdie, dated 14th May 2015.
For details of experiments see notes by Jordan Lane. 

Four sample concentrations, two lipid mixtures, four temperatures and two buffer types, results in 80 possible combinations. Only 67 of these were run and the following table indicates the complete set of data obtained from the Stopped Flow instrument.
<<test1,echo=FALSE>>=
sets[c("buffer","lipid","conc","temp","data")]
@

\newpage
\appendix
\section{Summary of data sets}

<<plots2,echo=FALSE,fig.width=12,fig.height=6,out.height="6cm",out.width='12cm'>>=
allplots
@



\end{document}